version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:71:8f:13:01:c5:17:1e:75:3c:ca:ed:4b:52:b6:86"
      - run: ssh -vvv -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "ls"
